version: "3"

services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: monitor
    volumes:
      - ./:/var/www/html
    networks:
      - monitor-network

#Docker Networks
networks:
  monitor-network:
    driver: bridge
